// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/search-jobs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/search-jobs.ts
var search_jobs_default = defineTool({
  name: "search_jobs",
  title: "Search jobs and internships",
  description: "Search active job and internship postings on Book My Mentor by keyword, location, or job type.",
  inputSchema: {
    query: z.string().trim().optional().describe("Role, skill, or company keyword."),
    location: z.string().trim().optional().describe("City name or 'remote'."),
    job_type: z.string().trim().optional().describe("e.g. full-time, internship."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, location, job_type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("job_postings").select(
      "id, title, company_name, location, job_type, experience_level, skills, salary_min, salary_max, currency, created_at"
    ).eq("is_active", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (query) q = q.or(`title.ilike.%${query}%,company_name.ilike.%${query}%,description.ilike.%${query}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    if (job_type) q = q.ilike("job_type", `%${job_type}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-job.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_job_default = defineTool2({
  name: "get_job",
  title: "Get job details",
  description: "Get the full details of a single job or internship posting by its id.",
  inputSchema: { job_id: z2.string().uuid().describe("The job posting id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("job_postings").select("*").eq("id", job_id).eq("is_active", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "No active job found with that id." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { job: data }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_courses_default = defineTool3({
  name: "list_courses",
  title: "List courses",
  description: "List the active courses offered by Book My Mentor, with price and duration.",
  inputSchema: {
    category: z3.string().trim().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("courses").select("id, title, description, category, duration, price, rating, features").eq("is_active", true);
    if (category) q = q.ilike("category", `%${category}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/my-applications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var my_applications_default = defineTool4({
  name: "my_applications",
  title: "My job applications",
  description: "List the signed-in user's job and internship applications and their status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("job_applications").select("id, job_id, status, created_at, job_postings(title, company_name, location)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/my-account.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
var my_account_default = defineTool5({
  name: "my_account",
  title: "My account overview",
  description: "Get the signed-in user's Book My Mentor account overview: profile, course orders, and jobs subscription status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, orders, subs] = await Promise.all([
      sb.from("profiles").select("id, full_name, email, phone").eq("id", userId).maybeSingle(),
      sb.from("orders").select("order_id, course_id, amount, status, invoice_number, created_at").eq("user_id", userId).order("created_at", { ascending: false }),
      sb.from("job_subscriptions").select("status, payment_status, starts_at, expires_at, amount").eq("user_id", userId).order("created_at", { ascending: false })
    ]);
    const firstError = profile.error || orders.error || subs.error;
    if (firstError)
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    const payload = {
      email: ctx.getUserEmail(),
      profile: profile.data,
      orders: orders.data ?? [],
      job_subscriptions: subs.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bratailqcgyaitflrdfq";
var mcp_default = defineMcp({
  name: "book-my-mentor",
  title: "book-my-mentor",
  version: "0.1.0",
  instructions: "Tools for Book My Mentor, an EdTech and HR-Tech platform. Use `search_jobs` and `get_job` for job and internship listings, `list_courses` for course offerings, and `my_applications` / `my_account` for the signed-in user's own applications, orders, and jobs subscription.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_jobs_default, get_job_default, list_courses_default, my_applications_default, my_account_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
