-- 1) 50% discount codes (unlimited time)
INSERT INTO public.coupons (coupon_code, discount_percent, discount_amount, discount_type, is_active, is_reusable, max_uses, valid_until, description)
VALUES 
  ('MAVEN30', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Wonder30', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Triump20', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Bliss40', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Marvel90', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Wizard26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Nayak', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('Talisman', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('EDUCATE50', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('EMERALD50', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('TOPAZ10', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('RUBY15', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('SAPPHIRE2', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('FLINT55', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('EREKA', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('QUARK', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMT25', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITB325', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITD725', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITJ525', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITG925', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITK225', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMK42', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('VJTI625', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('BITS464', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('NSUT33', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('SRCC22', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('MDI26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('SIBM26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMV26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMKZ36', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMAT26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITM226', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('GECA326', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IIMU26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('IITKGP26', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('XLRI46', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('TISS98', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('SJMSOM99', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),
  ('NMIMS36', 50, 0, 'percentage', true, true, null, null, 'Flat 50% discount'),

-- 2) 50% + Rs 2000 combination discount codes
  ('WINNER30', 50, 2000, 'combination', true, true, null, null, 'Flat 50% discount + Rs 2000 off'),
  ('FIESTA40', 50, 2000, 'combination', true, true, null, null, 'Flat 50% discount + Rs 2000 off'),
  ('TRIBBER20', 50, 2000, 'combination', true, true, null, null, 'Flat 50% discount + Rs 2000 off'),

-- 3) 30% discount codes (unlimited time)
  ('ELITE30', 30, 0, 'percentage', true, true, null, null, 'Flat 30% discount'),
  ('UNSTOP30', 30, 0, 'percentage', true, true, null, null, 'Flat 30% discount')
ON CONFLICT (coupon_code) DO UPDATE SET
  discount_percent = EXCLUDED.discount_percent,
  discount_amount = EXCLUDED.discount_amount,
  discount_type = EXCLUDED.discount_type,
  is_active = EXCLUDED.is_active,
  is_reusable = EXCLUDED.is_reusable,
  max_uses = EXCLUDED.max_uses,
  valid_until = EXCLUDED.valid_until,
  description = EXCLUDED.description;