-- Clear existing questions to avoid duplicates
DELETE FROM public.quiz_questions;

-- Product Management - Regular Plan Assessment (4eb187da-1f5b-45e2-b374-a650d1df8188)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index) VALUES
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is the primary goal of Product Management?', '[{"id": "a", "text": "Writing code for products"}, {"id": "b", "text": "Identifying customer needs and delivering value"}, {"id": "c", "text": "Managing team schedules"}, {"id": "d", "text": "Designing user interfaces"}]'::jsonb, 'b', 1, 1),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What does MVP stand for in product development?', '[{"id": "a", "text": "Most Valuable Player"}, {"id": "b", "text": "Minimum Viable Product"}, {"id": "c", "text": "Maximum Value Proposition"}, {"id": "d", "text": "Market Value Priority"}]'::jsonb, 'b', 1, 2),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'Which framework is commonly used in Agile product development?', '[{"id": "a", "text": "Waterfall"}, {"id": "b", "text": "Six Sigma"}, {"id": "c", "text": "Scrum"}, {"id": "d", "text": "ITIL"}]'::jsonb, 'c', 1, 3),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is a Product Roadmap?', '[{"id": "a", "text": "A map of company locations"}, {"id": "b", "text": "A strategic plan showing product direction over time"}, {"id": "c", "text": "A list of bugs to fix"}, {"id": "d", "text": "A customer contact list"}]'::jsonb, 'b', 1, 4),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is a User Persona?', '[{"id": "a", "text": "A fictional representation of target user"}, {"id": "b", "text": "A real customer profile"}, {"id": "c", "text": "A team member role"}, {"id": "d", "text": "A marketing budget"}]'::jsonb, 'a', 1, 5),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is Product-Market Fit?', '[{"id": "a", "text": "A manufacturing process"}, {"id": "b", "text": "When product satisfies strong market demand"}, {"id": "c", "text": "A pricing strategy"}, {"id": "d", "text": "A marketing campaign"}]'::jsonb, 'b', 1, 6),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is a Sprint in Agile?', '[{"id": "a", "text": "A running competition"}, {"id": "b", "text": "A fixed time period for completing work"}, {"id": "c", "text": "A marketing event"}, {"id": "d", "text": "A sales target"}]'::jsonb, 'b', 1, 7),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is a User Story?', '[{"id": "a", "text": "A novel about users"}, {"id": "b", "text": "A short description of feature from user perspective"}, {"id": "c", "text": "A customer complaint"}, {"id": "d", "text": "A sales pitch"}]'::jsonb, 'b', 1, 8),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is A/B Testing?', '[{"id": "a", "text": "Testing alphabets"}, {"id": "b", "text": "Comparing two versions to determine better performance"}, {"id": "c", "text": "A blood test"}, {"id": "d", "text": "A hiring process"}]'::jsonb, 'b', 1, 9),
('4eb187da-1f5b-45e2-b374-a650d1df8188', 'What is Customer Acquisition Cost (CAC)?', '[{"id": "a", "text": "Cost of customer service"}, {"id": "b", "text": "Cost to acquire a new customer"}, {"id": "c", "text": "Customer credit score"}, {"id": "d", "text": "Cost of manufacturing"}]'::jsonb, 'b', 1, 10);

-- Product Management - Advance Plan Assessment (34e2f16f-9fe6-4599-b1b4-78ca90d6a99f)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index) VALUES
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is the RICE prioritization framework?', '[{"id": "a", "text": "A cooking method"}, {"id": "b", "text": "Reach, Impact, Confidence, Effort scoring"}, {"id": "c", "text": "A database system"}, {"id": "d", "text": "A communication protocol"}]'::jsonb, 'b', 1, 1),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Product Discovery?', '[{"id": "a", "text": "Finding lost products"}, {"id": "b", "text": "Process of understanding user needs before building"}, {"id": "c", "text": "A marketing campaign"}, {"id": "d", "text": "Inventory management"}]'::jsonb, 'b', 1, 2),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is OKR in product management?', '[{"id": "a", "text": "Online Knowledge Repository"}, {"id": "b", "text": "Objectives and Key Results"}, {"id": "c", "text": "Operational Knowledge Review"}, {"id": "d", "text": "Order Key Requirements"}]'::jsonb, 'b', 1, 3),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Technical Debt?', '[{"id": "a", "text": "Money owed for technology"}, {"id": "b", "text": "Implied cost of rework from quick solutions"}, {"id": "c", "text": "IT budget"}, {"id": "d", "text": "Hardware maintenance cost"}]'::jsonb, 'b', 1, 4),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is the Jobs-to-be-Done (JTBD) framework?', '[{"id": "a", "text": "A hiring process"}, {"id": "b", "text": "Framework focusing on what customers want to accomplish"}, {"id": "c", "text": "A project management tool"}, {"id": "d", "text": "A scheduling software"}]'::jsonb, 'b', 1, 5),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is North Star Metric?', '[{"id": "a", "text": "An astronomy term"}, {"id": "b", "text": "Single metric that best captures core value delivered"}, {"id": "c", "text": "A navigation tool"}, {"id": "d", "text": "A performance review"}]'::jsonb, 'b', 1, 6),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Feature Flagging?', '[{"id": "a", "text": "Marking bugs"}, {"id": "b", "text": "Technique to enable/disable features without deployment"}, {"id": "c", "text": "A design pattern"}, {"id": "d", "text": "A code review process"}]'::jsonb, 'b', 1, 7),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Customer Lifetime Value (CLV)?', '[{"id": "a", "text": "Customer age"}, {"id": "b", "text": "Total revenue expected from a customer relationship"}, {"id": "c", "text": "Customer satisfaction score"}, {"id": "d", "text": "Number of purchases"}]'::jsonb, 'b', 1, 8),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Product Analytics?', '[{"id": "a", "text": "Product cost analysis"}, {"id": "b", "text": "Understanding user behavior through data"}, {"id": "c", "text": "Manufacturing metrics"}, {"id": "d", "text": "Sales forecasting"}]'::jsonb, 'b', 1, 9),
('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f', 'What is Cohort Analysis?', '[{"id": "a", "text": "Team performance review"}, {"id": "b", "text": "Analyzing groups with shared characteristics over time"}, {"id": "c", "text": "Budget planning"}, {"id": "d", "text": "Market segmentation only"}]'::jsonb, 'b', 1, 10);

-- Product Management - Premium Plan Assessment (547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index) VALUES
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Platform Product Management?', '[{"id": "a", "text": "Managing social media"}, {"id": "b", "text": "Building products used by other products/developers"}, {"id": "c", "text": "Operating systems only"}, {"id": "d", "text": "Hardware management"}]'::jsonb, 'b', 1, 1),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Growth Product Management?', '[{"id": "a", "text": "Physical product growth"}, {"id": "b", "text": "Driving user acquisition, activation, retention"}, {"id": "c", "text": "Revenue growth only"}, {"id": "d", "text": "Team size growth"}]'::jsonb, 'b', 1, 2),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Product-Led Growth (PLG)?', '[{"id": "a", "text": "Growing product features"}, {"id": "b", "text": "Using product as primary driver of customer acquisition"}, {"id": "c", "text": "Manufacturing efficiency"}, {"id": "d", "text": "Sales-led approach"}]'::jsonb, 'b', 1, 3),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is the AARRR (Pirate Metrics) framework?', '[{"id": "a", "text": "A sound pirates make"}, {"id": "b", "text": "Acquisition, Activation, Retention, Revenue, Referral"}, {"id": "c", "text": "A coding framework"}, {"id": "d", "text": "A design system"}]'::jsonb, 'b', 1, 4),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is API Product Management?', '[{"id": "a", "text": "Managing application interfaces as products"}, {"id": "b", "text": "Hardware management"}, {"id": "c", "text": "Network security"}, {"id": "d", "text": "Database administration"}]'::jsonb, 'a', 1, 5),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Product Operations (Product Ops)?', '[{"id": "a", "text": "Manufacturing operations"}, {"id": "b", "text": "Function supporting product team efficiency"}, {"id": "c", "text": "IT operations"}, {"id": "d", "text": "Customer operations"}]'::jsonb, 'b', 1, 6),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Product Sense in interviews?', '[{"id": "a", "text": "Physical product feel"}, {"id": "b", "text": "Ability to identify good product decisions"}, {"id": "c", "text": "Market research skills"}, {"id": "d", "text": "Technical coding ability"}]'::jsonb, 'b', 1, 7),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Outcome-based Product Management?', '[{"id": "a", "text": "Output-focused approach"}, {"id": "b", "text": "Measuring success by business outcomes not features"}, {"id": "c", "text": "Timeline management"}, {"id": "d", "text": "Resource allocation"}]'::jsonb, 'b', 1, 8),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Continuous Discovery?', '[{"id": "a", "text": "Constant product searching"}, {"id": "b", "text": "Regular customer research integrated into development"}, {"id": "c", "text": "Continuous deployment"}, {"id": "d", "text": "Bug discovery process"}]'::jsonb, 'b', 1, 9),
('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6', 'What is Product Vision vs Strategy?', '[{"id": "a", "text": "Same concept"}, {"id": "b", "text": "Vision is aspirational future; strategy is how to get there"}, {"id": "c", "text": "Strategy is long-term; vision is short-term"}, {"id": "d", "text": "Technical specifications"}]'::jsonb, 'b', 1, 10);

-- Lean Startup Assessment (e4af58b3-c102-470f-8577-dec96809a9ae)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index) VALUES
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is the Build-Measure-Learn loop?', '[{"id": "a", "text": "A construction process"}, {"id": "b", "text": "Cycle of creating, testing, and learning from experiments"}, {"id": "c", "text": "A learning management system"}, {"id": "d", "text": "A measurement tool"}]'::jsonb, 'b', 1, 1),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is a Pivot in Lean Startup?', '[{"id": "a", "text": "A basketball move"}, {"id": "b", "text": "Structured change in strategy based on learnings"}, {"id": "c", "text": "A financial term"}, {"id": "d", "text": "Office reorganization"}]'::jsonb, 'b', 1, 2),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is Validated Learning?', '[{"id": "a", "text": "Certified education"}, {"id": "b", "text": "Learning through scientific experiments"}, {"id": "c", "text": "Classroom training"}, {"id": "d", "text": "Book knowledge"}]'::jsonb, 'b', 1, 3),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is a Business Model Canvas (BMC)?', '[{"id": "a", "text": "A painting technique"}, {"id": "b", "text": "Strategic tool for developing business models"}, {"id": "c", "text": "A financial report"}, {"id": "d", "text": "An art project"}]'::jsonb, 'b', 1, 4),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What are Vanity Metrics?', '[{"id": "a", "text": "Beauty measurements"}, {"id": "b", "text": "Metrics that look good but dont drive decisions"}, {"id": "c", "text": "Important KPIs"}, {"id": "d", "text": "Financial metrics"}]'::jsonb, 'b', 1, 5),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is Customer Development?', '[{"id": "a", "text": "Training customers"}, {"id": "b", "text": "Process of understanding customer needs through interaction"}, {"id": "c", "text": "Customer service"}, {"id": "d", "text": "Sales process"}]'::jsonb, 'b', 1, 6),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is Innovation Accounting?', '[{"id": "a", "text": "Creative bookkeeping"}, {"id": "b", "text": "Measuring progress in uncertain conditions"}, {"id": "c", "text": "Tax calculations"}, {"id": "d", "text": "Budget planning"}]'::jsonb, 'b', 1, 7),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is a Lean Canvas?', '[{"id": "a", "text": "A thin painting surface"}, {"id": "b", "text": "Adapted business model canvas for startups"}, {"id": "c", "text": "A diet plan"}, {"id": "d", "text": "A fitness program"}]'::jsonb, 'b', 1, 8),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is the Concierge MVP?', '[{"id": "a", "text": "A hotel service"}, {"id": "b", "text": "Manually delivering solution before building product"}, {"id": "c", "text": "A luxury product"}, {"id": "d", "text": "A customer service role"}]'::jsonb, 'b', 1, 9),
('e4af58b3-c102-470f-8577-dec96809a9ae', 'What is Problem-Solution Fit?', '[{"id": "a", "text": "Matching puzzles"}, {"id": "b", "text": "When solution effectively addresses customer problem"}, {"id": "c", "text": "A hiring process"}, {"id": "d", "text": "Technical compatibility"}]'::jsonb, 'b', 1, 10);

-- Project Management Assessment (b78b6b83-bf7f-4571-98e9-e5fc6a1b960a)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index) VALUES
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is the Project Management Triangle?', '[{"id": "a", "text": "A geometric shape"}, {"id": "b", "text": "Scope, Time, Cost constraints"}, {"id": "c", "text": "A team structure"}, {"id": "d", "text": "An office layout"}]'::jsonb, 'b', 1, 1),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is a Work Breakdown Structure (WBS)?', '[{"id": "a", "text": "Employee stress analysis"}, {"id": "b", "text": "Hierarchical decomposition of project deliverables"}, {"id": "c", "text": "Office organization chart"}, {"id": "d", "text": "Budget breakdown"}]'::jsonb, 'b', 1, 2),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is a Gantt Chart?', '[{"id": "a", "text": "A pie chart"}, {"id": "b", "text": "Visual timeline of project schedule"}, {"id": "c", "text": "A bar graph of sales"}, {"id": "d", "text": "An organizational chart"}]'::jsonb, 'b', 1, 3),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Critical Path Method (CPM)?', '[{"id": "a", "text": "Emergency procedures"}, {"id": "b", "text": "Technique to identify longest path determining project duration"}, {"id": "c", "text": "Safety protocols"}, {"id": "d", "text": "Communication method"}]'::jsonb, 'b', 1, 4),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Stakeholder Management?', '[{"id": "a", "text": "Managing shareholders only"}, {"id": "b", "text": "Engaging people affected by project decisions"}, {"id": "c", "text": "Managing investors"}, {"id": "d", "text": "HR management"}]'::jsonb, 'b', 1, 5),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Risk Management in projects?', '[{"id": "a", "text": "Taking dangerous actions"}, {"id": "b", "text": "Identifying, assessing, and mitigating potential risks"}, {"id": "c", "text": "Avoiding all decisions"}, {"id": "d", "text": "Insurance policies only"}]'::jsonb, 'b', 1, 6),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Resource Leveling?', '[{"id": "a", "text": "Flattening resources physically"}, {"id": "b", "text": "Resolving resource conflicts by adjusting schedule"}, {"id": "c", "text": "Hiring equally"}, {"id": "d", "text": "Budget balancing"}]'::jsonb, 'b', 1, 7),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Earned Value Management (EVM)?', '[{"id": "a", "text": "Employee bonuses"}, {"id": "b", "text": "Technique measuring project performance against plan"}, {"id": "c", "text": "Revenue calculation"}, {"id": "d", "text": "Stock valuation"}]'::jsonb, 'b', 1, 8),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is a Project Charter?', '[{"id": "a", "text": "A company airplane"}, {"id": "b", "text": "Document authorizing project and defining scope"}, {"id": "c", "text": "A team contract"}, {"id": "d", "text": "A legal agreement"}]'::jsonb, 'b', 1, 9),
('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a', 'What is Change Management in projects?', '[{"id": "a", "text": "Changing money"}, {"id": "b", "text": "Structured approach to handling project changes"}, {"id": "c", "text": "Switching jobs"}, {"id": "d", "text": "Office relocation"}]'::jsonb, 'b', 1, 10);