
UPDATE public.quizzes SET passing_score = 70, time_limit_minutes = 20;
DELETE FROM public.quiz_questions;

WITH map(quiz_id, topic) AS (VALUES
 ('34e2f16f-9fe6-4599-b1b4-78ca90d6a99f'::uuid,'pm'),
 ('547c5bb1-9be1-4f20-b7c3-7a82f20c9ed6'::uuid,'pm'),
 ('4eb187da-1f5b-45e2-b374-a650d1df8188'::uuid,'pm'),
 ('e4af58b3-c102-470f-8577-dec96809a9ae'::uuid,'lean'),
 ('b78b6b83-bf7f-4571-98e9-e5fc6a1b960a'::uuid,'pmp')
), q(topic, oi, qt, opts, ans) AS (VALUES
('pm',1,'Weekly active accounts are flat while seats per account grew 18%. What is the strongest interpretation?','[{"id":"a","text":"Acquisition improved sharply and retention clearly deteriorated this quarter"},{"id":"b","text":"The activation funnel is broken and pricing must be cut immediately"},{"id":"c","text":"Existing accounts deepened adoption while new account acquisition stayed flat"},{"id":"d","text":"The two metrics always move together, so the data is unusable"}]'::jsonb,'c'),
('pm',2,'You must sequence work under a fixed deadline with very different costs of delay. Which framework fits best?','[{"id":"a","text":"RICE, because reach and confidence dominate deadline-driven sequencing"},{"id":"b","text":"MoSCoW, because it separates must-have items from nice-to-have items"},{"id":"c","text":"Kano, because delight features drive the most revenue near deadlines"},{"id":"d","text":"WSJF, because it divides cost of delay by the size of the job"}]'::jsonb,'d'),
('pm',3,'A marketplace has strong supply but weak demand. Best North Star metric?','[{"id":"a","text":"Weekly completed transactions per active buyer cohort"},{"id":"b","text":"Total number of registered suppliers added each month"},{"id":"c","text":"Cumulative app downloads reported across all app stores"},{"id":"d","text":"Average time suppliers spend inside the seller dashboard"}]'::jsonb,'a'),
('pm',4,'An A/B test shows +6% conversion at p=0.14 after four days on 30% traffic. Correct action?','[{"id":"a","text":"Ship immediately since the observed lift is commercially meaningful"},{"id":"b","text":"Keep running until the pre-registered sample size and duration complete"},{"id":"c","text":"Stop the test and declare the variant a confirmed failure"},{"id":"d","text":"Re-slice the data until one segment reaches statistical significance"}]'::jsonb,'b'),
('pm',5,'Which statement best describes product strategy, as distinct from a roadmap?','[{"id":"a","text":"A dated list of features committed to leadership each quarter"},{"id":"b","text":"A prioritised backlog refined with engineering every two weeks"},{"id":"c","text":"A diagnosis, a guiding policy, and coherent actions toward an outcome"},{"id":"d","text":"A quarterly OKR sheet listing team targets and named owners"}]'::jsonb,'c'),
('pm',6,'Churn is concentrated in month two for self-serve users. Highest leverage intervention?','[{"id":"a","text":"Increase paid acquisition spend on the best performing channel"},{"id":"b","text":"Add a new premium tier priced above the current top plan"},{"id":"c","text":"Redesign the marketing homepage with clearer positioning copy"},{"id":"d","text":"Rebuild onboarding around the habit-forming activation moment"}]'::jsonb,'d'),
('pm',7,'Which pricing move tests willingness to pay without damaging customer trust?','[{"id":"a","text":"Silently raising prices for existing customers at renewal time"},{"id":"b","text":"Running a price experiment on new customers with grandfathering"},{"id":"c","text":"Removing features from the plan customers have already bought"},{"id":"d","text":"Offering permanent discounts to every inbound lead this quarter"}]'::jsonb,'b'),
('pm',8,'Engineering requests a two-quarter platform rewrite. What does a strong PM do first?','[{"id":"a","text":"Quantify the cost of the status quo against roadmap opportunity cost"},{"id":"b","text":"Approve it because engineering alone owns technical decisions"},{"id":"c","text":"Reject it and push customer-facing features for the whole year"},{"id":"d","text":"Escalate to leadership immediately without gathering any evidence"}]'::jsonb,'a'),
('pm',9,'Which is the strongest signal that a feature reached product-market fit in a segment?','[{"id":"a","text":"High click-through on the in-app announcement banner at launch"},{"id":"b","text":"Positive comments collected from a handful of friendly customers"},{"id":"c","text":"Sustained repeat usage and retention lift in that segment cohorts"},{"id":"d","text":"A spike in demo requests during the launch week campaign"}]'::jsonb,'c'),
('pm',10,'Two senior stakeholders demand conflicting features with equal urgency. Best approach?','[{"id":"a","text":"Build both partially so neither stakeholder feels ignored this quarter"},{"id":"b","text":"Let the loudest executive decide to reduce internal political friction"},{"id":"c","text":"Defer the decision until the next annual planning cycle begins"},{"id":"d","text":"Test each against the strategy and expected outcome, then decide"}]'::jsonb,'d'),
('lean',1,'For a new two-sided marketplace, the riskiest assumption is usually whether','[{"id":"a","text":"the engineering team can ship the full platform on time"},{"id":"b","text":"the value exchange is desirable enough for people to repeat it"},{"id":"c","text":"the brand name is memorable inside the target market"},{"id":"d","text":"the investor deck communicates the long-term vision clearly"}]'::jsonb,'b'),
('lean',2,'Which of these is a genuine innovation accounting metric?','[{"id":"a","text":"Total funding raised across the seed and pre-seed rounds"},{"id":"b","text":"Number of features shipped by the team in every sprint"},{"id":"c","text":"Cumulative signups counted since the product first launched"},{"id":"d","text":"Cohort conversion improvement between successive experiments"}]'::jsonb,'d'),
('lean',3,'A concierge MVP is most appropriate when','[{"id":"a","text":"the value hypothesis is unproven and delivery can be done manually"},{"id":"b","text":"the product already shows strong retention across several cohorts"},{"id":"c","text":"the engineering team needs a scalable architecture immediately"},{"id":"d","text":"the company must reduce its support headcount as fast as possible"}]'::jsonb,'a'),
('lean',4,'Which of the following is a vanity metric?','[{"id":"a","text":"Repeat purchase rate measured within a weekly cohort"},{"id":"b","text":"Paid conversion rate from trial within fourteen days"},{"id":"c","text":"Cumulative total registered users since the launch day"},{"id":"d","text":"Net revenue retention across the enterprise segment"}]'::jsonb,'c'),
('lean',5,'Five interviewees praised your idea but none pre-paid. Best interpretation?','[{"id":"a","text":"Desirability is validated and the team should scale spending now"},{"id":"b","text":"Stated preference is weak evidence and behavioural commitment failed"},{"id":"c","text":"The interview sample was simply too small to mean anything at all"},{"id":"d","text":"Pricing is irrelevant at this early stage of customer discovery"}]'::jsonb,'b'),
('lean',6,'A pivot is genuinely justified when','[{"id":"a","text":"the board asks for faster revenue growth in the next quarter"},{"id":"b","text":"a competitor launches a similar feature in an adjacent market"},{"id":"c","text":"the team feels bored working in the current problem space"},{"id":"d","text":"repeated experiments fail to move the engine of growth"}]'::jsonb,'d'),
('lean',7,'Which growth engine depends on margin from a customer exceeding acquisition cost?','[{"id":"a","text":"Paid growth, funded by margin exceeding the cost of acquisition"},{"id":"b","text":"Viral growth, driven by product-native invitation loops"},{"id":"c","text":"Sticky growth, driven by retention exceeding the churn rate"},{"id":"d","text":"Organic growth, driven by search and content distribution"}]'::jsonb,'a'),
('lean',8,'Which hypothesis is properly falsifiable?','[{"id":"a","text":"Users will probably love the redesigned onboarding experience"},{"id":"b","text":"Our product is better than every competitor in the market"},{"id":"c","text":"30% of new signups will complete setup within ten minutes"},{"id":"d","text":"Improving the interface will increase satisfaction for all users"}]'::jsonb,'c'),
('lean',9,'A smoke test converts at 12%, but the traffic came from existing customers. Main flaw?','[{"id":"a","text":"The sample size was far too small to draw any conclusion"},{"id":"b","text":"Selection bias, because that audience already trusts the brand"},{"id":"c","text":"The landing page was not optimised for mobile visitors"},{"id":"d","text":"Conversion rate is meaningless during early-stage validation"}]'::jsonb,'b'),
('lean',10,'The primary purpose of an MVP is to','[{"id":"a","text":"launch the cheapest possible version in order to save runway"},{"id":"b","text":"impress investors with a polished early product demonstration"},{"id":"c","text":"ship the smallest slice of the full feature roadmap"},{"id":"d","text":"maximise validated learning per unit of effort spent"}]'::jsonb,'d'),
('pmp',1,'The critical path is 42 days. A task with 5 days of float slips by 8 days. Result?','[{"id":"a","text":"No effect, because non-critical tasks never affect the schedule"},{"id":"b","text":"The project finishes eight days later than originally planned"},{"id":"c","text":"That path becomes critical and the schedule slips three days"},{"id":"d","text":"Total float across the whole network increases by three days"}]'::jsonb,'c'),
('pmp',2,'Earned value 80k, planned value 100k, actual cost 90k. Which statement is correct?','[{"id":"a","text":"The project is behind schedule and over budget"},{"id":"b","text":"The project is ahead of schedule and under budget"},{"id":"c","text":"The project is on schedule but slightly over budget"},{"id":"d","text":"The cost performance index equals one point one one"}]'::jsonb,'a'),
('pmp',3,'Best response to a high-probability, high-impact threat that cannot be reduced?','[{"id":"a","text":"Accept it passively and add contingency to the overall budget"},{"id":"b","text":"Mitigate it by adding more people to the critical tasks"},{"id":"c","text":"Escalate it to the sponsor without any documented analysis"},{"id":"d","text":"Avoid it by changing scope or approach to remove the exposure"}]'::jsonb,'d'),
('pmp',4,'A stakeholder with high power and low interest should be','[{"id":"a","text":"managed closely with daily updates and detailed status reports"},{"id":"b","text":"kept satisfied with concise, decision-relevant communication"},{"id":"c","text":"monitored passively with no structured communication at all"},{"id":"d","text":"informed only through the general project newsletter"}]'::jsonb,'b'),
('pmp',5,'Scope creep is best prevented by','[{"id":"a","text":"refusing every change request raised after project kickoff"},{"id":"b","text":"adding buffer to every task estimate in the schedule"},{"id":"c","text":"an enforced change control process tied to the baseline"},{"id":"d","text":"shortening the timeline so fewer requests can be raised"}]'::jsonb,'c'),
('pmp',6,'In a hybrid delivery model, fixed-scope regulatory work is best handled with','[{"id":"a","text":"a predictive plan with formal baselines and stage gates"},{"id":"b","text":"a Kanban board with work-in-progress limits only"},{"id":"c","text":"two-week sprints with continuously reprioritised scope"},{"id":"d","text":"an informal backlog owned by the delivery manager"}]'::jsonb,'a'),
('pmp',7,'Velocity dropped 40% after two members left mid-release. First action?','[{"id":"a","text":"Push the team into overtime until velocity fully recovers"},{"id":"b","text":"Re-forecast the release and renegotiate scope with stakeholders"},{"id":"c","text":"Split stories further so the burndown chart looks healthier"},{"id":"d","text":"Hire contractors immediately without revisiting the forecast"}]'::jsonb,'b'),
('pmp',8,'The purpose of a RACI matrix is to','[{"id":"a","text":"track budget consumption across the project life cycle"},{"id":"b","text":"sequence dependent activities along the critical path"},{"id":"c","text":"record identified risks with owners and response plans"},{"id":"d","text":"clarify responsibility, accountability, consultation and information"}]'::jsonb,'d'),
('pmp',9,'When the current cost variance is typical, estimate at completion equals','[{"id":"a","text":"budget at completion minus the actual cost incurred to date"},{"id":"b","text":"actual cost plus the remaining planned value amount"},{"id":"c","text":"budget at completion divided by the cost performance index"},{"id":"d","text":"planned value multiplied by the schedule performance index"}]'::jsonb,'c'),
('pmp',10,'Lessons learned deliver the most value when they are','[{"id":"a","text":"captured continuously and applied to live project decisions"},{"id":"b","text":"written only during the formal project closure phase"},{"id":"c","text":"stored in an archive that few team members ever access"},{"id":"d","text":"shared verbally in the final stakeholder steering meeting"}]'::jsonb,'a')
)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option_id, points, order_index)
SELECT m.quiz_id, q.qt, q.opts, q.ans, 1, q.oi FROM map m JOIN q ON q.topic = m.topic;

WITH cmap(course_id, topic) AS (VALUES
 ('7331cd2f-8d0a-4226-81e7-25ddd50e8cbd'::uuid,'pm'),
 ('6b43cc09-8e4f-4612-8761-c043c903c671'::uuid,'pm'),
 ('a991cf65-a9fb-4e11-b9d0-4c28c98bf1af'::uuid,'pm'),
 ('97dd9dd1-64f7-4008-a2cf-4384f8327e9e'::uuid,'lean'),
 ('ccf8b2b7-d2b9-4c33-9f3a-49543f43e7ee'::uuid,'pmp')
), iq(topic, oi, question, answer_outline, difficulty, category) AS (VALUES
('pm',1,'Our activation rate fell from 42% to 31% in six weeks with no release changes. How would you find the cause in 48 hours?','Segment by channel, device, geography and cohort start date; check instrumentation integrity first; compare funnel step conversion before and after; overlay marketing mix shifts and any third-party outage; form two competing hypotheses and disprove the cheaper one first; report with a decision, not just data.','Hard','Analytics & Metrics'),
('pm',2,'Design the pricing for a product used daily by one team but paid for by a CFO. Which value metric would you choose and why?','Separate user (team) from buyer (CFO); pick a value metric that scales with realised outcome, not seats alone; model expansion and downgrade paths; grandfather existing accounts; test on new logos only; state guardrail metrics such as win rate and net revenue retention.','Hard','Pricing & Monetisation'),
('pm',3,'You have three months of runway and two strategic bets. How do you choose?','Frame each as a hypothesis with a measurable kill criterion; estimate cost of delay and reversibility; prefer the reversible, cheaper-to-test bet first; sequence so learning from one informs the other; commit explicit stop rules before starting.','Hard','Strategy & Prioritisation'),
('pm',4,'Engineering estimates 10 weeks; sales promised the customer 4 weeks. Walk me through your next 24 hours.','Do not renegotiate physics; clarify the customer outcome behind the promise; find the thinnest slice that delivers that outcome; present options with explicit trade-offs and risks to both sides; agree a single owner for the commitment; document the decision and the debt created.','Hard','Stakeholder Management'),
('pm',5,'How would you design an experiment where the metric you care about only moves after 90 days?','Use a leading indicator validated as correlated with the lagging metric; run a holdout group; consider switchback or geo tests when contamination is likely; pre-register sample size and duration; guard against novelty effect and seasonality.','Expert','Experimentation'),
('pm',6,'Tell me about a product decision you got wrong. What was the second-order effect you missed?','Pick a real decision; state the hypothesis, the evidence you had, and the evidence you skipped; name the second-order effect (support load, sales incentive, churn in a segment); explain the detection lag and the systemic fix you installed afterwards.','Hard','Behavioural'),
('lean',1,'You have Rs 50,000 and four weeks to validate a B2C idea. What exactly do you spend it on?','Allocate to demand tests, not build: smoke-test landing pages, paid traffic on two positioning angles, 15 problem interviews, and a concierge delivery for the first 10 buyers; define a pre-committed pass/fail conversion threshold before spending.','Hard','Validation'),
('lean',2,'How do you distinguish a false negative experiment from a genuinely dead idea?','Check the experiment quality first: audience match, message clarity, offer strength, traffic volume, tracking; rerun with one variable changed; only conclude the idea is dead after the riskiest assumption fails across independent tests.','Expert','Experimentation'),
('lean',3,'Your MVP has 60% week-one retention but 8% week-four retention. What do you do?','Investigate the habit loop and the frequency of the underlying need; interview churned users within 72 hours; map the value moment against natural usage cadence; decide between a zoom-in pivot, a segment pivot, or repositioning.','Hard','Retention'),
('lean',4,'Describe an ethical line you would not cross while running growth experiments.','Discuss informed consent, dark patterns, price discrimination, data privacy, and experimenting on vulnerable users; explain guardrail metrics and an escalation path; show that trust is a long-term growth asset.','Hard','Ethics & Judgement'),
('lean',5,'When would you deliberately choose to build something that does not scale?','When learning velocity matters more than efficiency: manual onboarding, hand-matched supply, founder-led sales; set an explicit exit trigger (volume or cost per unit) at which automation begins.','Hard','Operations'),
('lean',6,'Your best growth channel saturates. How do you plan the next one?','Diagnose saturation with CAC and frequency curves; map channel-model fit against price point and sales cycle; run two channel tests with equal budget and a clear success bar; protect the core channel while testing.','Expert','Growth'),
('pmp',1,'A vendor will miss a milestone that sits on the critical path. What do you do in the first hour, day, and week?','Hour: confirm facts and quantify schedule impact. Day: model crash vs fast-track options with cost and risk, inform the sponsor with options not just problems. Week: rebaseline if approved, update the risk register, add contractual remedies and earlier warning signals.','Hard','Schedule & Risk'),
('pmp',2,'CPI is 0.82 and SPI is 0.95 at 40% completion. What is your recovery plan?','Explain the cost overrun trend and forecast EAC using BAC/CPI; identify variance drivers by work package; choose between scope reduction, resource re-mix, and re-negotiation; avoid crashing costs further; present recovery options with confidence ranges.','Expert','Earned Value'),
('pmp',3,'How do you run a project where the sponsor changes priorities every two weeks?','Install a change control process with an agreed cadence and cost of change transparency; convert priority churn into a visible backlog trade-off; use short delivery increments to absorb change; escalate only with quantified impact.','Hard','Governance'),
('pmp',4,'Two teams blame each other for a defect that reached production. How do you handle it?','Run a blameless post-incident review; separate the timeline from the interpretation; fix the process gap (ownership, test gates, handover contract); assign one accountable owner; follow up publicly on the actions.','Hard','Leadership'),
('pmp',5,'When is agile the wrong choice, and how do you argue that with an agile-first leadership team?','Fixed regulatory scope, hard external deadlines, or high integration and compliance overhead favour predictive or hybrid delivery; argue with delivery risk data, not ideology; propose hybrid: predictive baselines with iterative build.','Expert','Methodology'),
('pmp',6,'How do you estimate a project with no historical data?','Use analogous estimation from adjacent domains, three-point PERT estimates, and a decomposition of the riskiest work packages; run a spike to reduce uncertainty; publish estimate ranges with confidence levels and revise at each gate.','Hard','Estimation')
)
INSERT INTO public.course_interview_questions (course_id, question, answer_outline, difficulty, category, order_index)
SELECT c.course_id, iq.question, iq.answer_outline, iq.difficulty, iq.category, iq.oi FROM cmap c JOIN iq ON iq.topic = c.topic;

WITH cmap(course_id, topic) AS (VALUES
 ('7331cd2f-8d0a-4226-81e7-25ddd50e8cbd'::uuid,'pm'),
 ('6b43cc09-8e4f-4612-8761-c043c903c671'::uuid,'pm'),
 ('a991cf65-a9fb-4e11-b9d0-4c28c98bf1af'::uuid,'pm'),
 ('97dd9dd1-64f7-4008-a2cf-4384f8327e9e'::uuid,'lean'),
 ('ccf8b2b7-d2b9-4c33-9f3a-49543f43e7ee'::uuid,'pmp')
), cs(topic, oi, title, scenario, challenge, tasks, hint, difficulty) AS (VALUES
('pm',1,'The Quiet Churn of a Fintech Super App','A fintech app with 2.1 million monthly users sees flat revenue while transactions per user fall 14% over two quarters. Support tickets are stable, NPS is unchanged, and a competitor recently launched instant UPI refunds.','Revenue looks safe today but usage depth is collapsing quietly. You must find the leak before it reaches the top line and defend a plan with limited engineering capacity.', ARRAY['Define the three cohorts you would analyse first and why','Separate competitive substitution from internal product decay','Propose one reversible experiment with a kill criterion','State the guardrail metric you would never trade away'],'Depth metrics usually break before revenue does. Look at frequency by use case, not overall averages.','Advanced'),
('pm',2,'Pricing a Zero-to-One AI Feature','Your team built an AI assistant that saves each user roughly four hours a week. Leadership wants it bundled free to drive adoption; finance wants a premium add-on priced at 40% of the base plan.','Both positions are defensible. You must design a pricing path that captures value without stalling adoption or triggering churn in price-sensitive segments.', ARRAY['Choose a value metric and justify it against two alternatives','Design a 6-week price test that protects existing customers','Define the adoption and monetisation guardrails','Explain the rollback plan if net revenue retention drops'],'Adoption and monetisation are sequenced problems, not opposing ones.','Advanced'),
('pm',3,'Rescuing a Roadmap After a 30% Budget Cut','Mid-year, your roadmap loses 30% of its budget. Three committed enterprise deals depend on two features; a platform migration is half complete; the team is showing burnout signals.','You must recut the plan in one week and communicate it without losing enterprise trust or team morale.', ARRAY['Rank the work using cost of delay and contractual risk','Decide what to stop entirely rather than slow down','Draft the message to the enterprise customers','Define what you will measure to prove the recut worked'],'Half-finished migrations are usually the most expensive thing to slow down.','Expert'),
('lean',1,'Two-Sided Cold Start in Tier-2 Cities','A local services marketplace has 400 verified providers in Indore but only 60 weekly bookings. Providers are churning because demand is thin, and paid ads convert at 0.6%.','Classic cold start. You must decide where to concentrate scarce resources to create a repeatable liquidity loop before the supply side collapses.', ARRAY['Choose one neighbourhood-and-category wedge and defend it','Design a concierge experiment to force liquidity manually','Define the liquidity metric and its weekly target','Specify the signal that would make you pivot the model'],'Liquidity is local. Average marketplace metrics hide the only pocket that works.','Advanced'),
('lean',2,'The Interview That Lied','After 22 customer interviews, 19 people said they would pay Rs 999 per month for your product. Your smoke test landing page converted 1.1%, and only two people entered card details.','Stated intent and revealed behaviour disagree sharply. You must decide whether the idea, the offer, the audience, or the test is broken.', ARRAY['List four possible causes and rank them by testability','Redesign the smoke test to remove the biggest bias','Define your pass and fail thresholds in advance','Decide the pivot option you would trigger on failure'],'Interviews validate problems; only behaviour validates offers.','Advanced'),
('lean',3,'Scaling Too Early','A D2C brand raised funding and scaled ad spend 5x. CAC rose from Rs 480 to Rs 1,320, repeat purchase rate fell from 34% to 19%, and inventory holding doubled.','Growth spending has outrun product-market fit. You must design a controlled retreat that preserves the healthy core of the business.', ARRAY['Identify which cohort still has healthy unit economics','Design the spend cut sequence and its measurement window','Propose two retention experiments before re-scaling','Set the re-scale trigger with a specific numeric bar'],'Find the cohort that was profitable before the scale-up and rebuild outward from it.','Expert'),
('pmp',1,'The 90-Day Regulatory Deadline','A banking client must deliver a compliance change in 90 days or face penalties. Discovery consumed 30 days, three critical integrations are unconfirmed, and the vendor contract has no penalty clause.','A hard external deadline with soft internal control. You must build a plan that survives contact with reality and a governance model that surfaces slippage early.', ARRAY['Build the critical path and name the top three schedule risks','Choose predictive, agile, or hybrid delivery and justify it','Design the escalation and early-warning mechanism','Define the minimum compliant scope you would protect'],'When the date cannot move, scope and risk response are your only real levers.','Advanced'),
('pmp',2,'Earned Value Tells an Ugly Story','At 45% completion, a 2.4 crore infrastructure project reports CPI 0.79 and SPI 1.02. The team is ahead of schedule but burning cash, and the sponsor wants the forecast in 48 hours.','Speed is being bought with money. You must forecast honestly and present recovery options that the sponsor can actually approve.', ARRAY['Forecast the estimate at completion and show your method','Explain what the CPI and SPI combination implies operationally','Present three recovery options with cost and risk trade-offs','Recommend one option and state your confidence level'],'A high SPI with a low CPI usually means resources are being over-applied to stay on schedule.','Expert'),
('pmp',3,'The Team That Stopped Talking','A distributed team across three time zones is missing sprint goals. Stand-ups are silent, defects are rising, and two senior engineers have quietly started refusing code reviews from one another.','The schedule problem is a symptom; the real risk is team dysfunction. You must repair collaboration without slowing delivery further.', ARRAY['Diagnose the likely root causes and how you would confirm them','Redesign the communication cadence across time zones','Define a conflict resolution step you would run this week','Choose the metrics that would prove the situation improved'],'Delivery metrics lag behind trust metrics. Fix the handover contract before adding process.','Advanced')
)
INSERT INTO public.course_case_studies (course_id, title, scenario, challenge, tasks, hint, difficulty, order_index)
SELECT c.course_id, cs.title, cs.scenario, cs.challenge, cs.tasks, cs.hint, cs.difficulty, cs.oi FROM cmap c JOIN cs ON cs.topic = c.topic;
