// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bratailqcgyaitflrdfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyYXRhaWxxY2d5YWl0ZmxyZGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDUyMTUsImV4cCI6MjA2NjMyMTIxNX0.39IeoYt9T0EwLYzrteFYEGEOLGE8EZLhvRehfLxXpFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);